### ISSUE TITLE
Fatal error preventing checkout to render! 

### ISSUE THREAD

**Issue by d9media** [easydigitaldownloads/themedd#221]
There is a serious issue right now on our checkout page. It stops right where cross-sell items should display. 

```
<div itemscope itemtype="http://schema.org/Product" class="<br />
<b>Fatal error</b>:  Uncaught ArgumentCountError: Too few arguments to function themedd_edd_download_class(), 3 passed in /var/www/vhosts/ourstore.com/httpdocs/wp-includes/class-wp-hook.php on line 286 and exactly 4 expected in /var/www/vhosts/ourstore.com/httpdocs/wp-content/themes/themedd/includes/compatibility/edd/filters.php:193
Stack trace:
#0 /var/www/vhosts/ourstore.com/httpdocs/wp-includes/class-wp-hook.php(286): themedd_edd_download_class('edd_download', '', '')
#1 /var/www/vhosts/ourstore.com/httpdocs/wp-includes/plugin.php(203): WP_Hook-&gt;apply_filters('edd_download', Array)
#2 /var/www/vhosts/ourstore.com/httpdocs/wp-content/plugins/edd-cross-sell-upsell/includes/template-functions.php(166): apply_filters('edd_download_cl...', 'edd_download', '', '')
#3 /var/www/vhosts/ourstore.com/httpdocs/wp-content/plugins/edd-cross-sell-upsell/includes/template-functions.php(253): edd_csau_html()
#4 /var/www/vhosts/ourstore.com/httpdocs/wp-includes/class-wp-hook.php(286): edd_csau_display_on_checkout_page('')
#5 /var/www/vhosts/aud in <b>/var/www/vhosts/ourstore.com/httpdocs/wp-content/themes/themedd/includes/compatibility/edd/filters.php</b> on line <b>193</b><br />
```

**Comment by d9media** [comment]
Thank you @SDavisMedia for your support. 

Actually as far I see we are running the latest versions. The fatal error disappeared when I disabled Cross-Sells. I'll investigate in our code whether there could be any customization that causes an error but even so, it's a bit odd that stacktrace does not indicate it.

**Comment by d9media** [comment]
For further testing, I'll have to mirror the site first and then report back with the method you were suggesting.

**Comment by SDavisMedia** [comment]
Okay great. I'll revisit again shortly to see if I can find a way to replicate the issue.
