### ISSUE TITLE
Themedd + Cross Sell + PHP 7.1+ causes Fatal error: Uncaught ArgumentCountError

### ISSUE THREAD

**Issue by dgoldak** [easydigitaldownloads/themedd#235]
Themedd + Cross Sell + PHP 7.1+ causes Fatal error: Uncaught ArgumentCountError

Fatal error: Uncaught ArgumentCountError: Too few arguments to function themedd_edd_download_class(), 3 passed in /app/public/wp-includes/class-wp-hook.php on line 286 and exactly 4 expected in /app/public/wp-content/themes/themedd/includes/compatibility/edd/filters.php:193 Stack trace: #0 /app/public/wp-includes/class-wp-hook.php(286): themedd_edd_download_class('edd_download', '', '') #1 /app/public/wp-includes/plugin.php(208): WP_Hook->apply_filters('edd_download', Array) #2 /app/public/wp-content/plugins/edd-cross-sell-upsell/includes/template-functions.php(166): apply_filters('edd_download_cl...', 'edd_download', '', '') #3 /app/public/wp-content/plugins/edd-cross-sell-upsell/includes/template-functions.php(280): edd_csau_html() #4 /app/public/wp-includes/class-wp-hook.php(286): edd_csau_single_download_upsells('<p>ba bala blal...') #5 /app/public/wp-includes/plugin.php(208): WP_Hook->apply_filters('<p>ba bala blal...', Array) #6 /app/public/wp-includes/post-template.php(247): apply_filters('the_content', 'ba bala bl in /app/public/wp-content/themes/themedd/includes/compatibility/edd/filters.php on line 193. Output triggered in /app/public/wp-content/plugins/query-monitor/collectors/php_errors.php on line 166 Call Stack #TimeMemoryFunctionLocation 10.46517826648QM_Collector_PHP_Errors->shutdown_handler( ).../php_errors.php:0 20.46517830592xdebug_print_function_stack ( ).../php_errors.php:166

Replicate Steps:
1. Activate Themedd
2. Enable Cross Sell Upsell for a product
3. PHP 7.1, 7.2 or 7.3
4. Navigate to product page and checkout page. No PHP errors should occur.

**Comment by cklosowski** [comment]
Is this something from themedd or CSUS @amdrew? Seems like we maybe changed
a themedd function in a way that wasn't backwards compatible?

**Comment by kerijacoby** [comment]
There's been a customer report of this and I replicated as well.

EDD Version 2.9.16
Cross-sell/Upsell Version 1.1.7
Themedd Version 1.0.7
PHP Version 7.3.2

Lowering the PHP Version to 7.0.3 fixes the issue.

https://secure.helpscout.net/conversation/967877397/132917?folderId=180504

**Comment by mintplugins** [comment]
As far back as I can trace this, EDD has always had 4 paramaters for the `edd_download_class` filter:
https://github.com/easydigitaldownloads/easy-digital-downloads/blame/26b70ddc7de645bcb0783aa887eacae5eec2882e/templates/shortcode-download.php#L18

Keeping in line with that, Themedd passes 4 paramaters to the filter here:
https://github.com/easydigitaldownloads/themedd/blob/master/includes/compatibility/edd/filters.php#L193

But Cross Sell and Upsell only pulls 3 of those paramaters in when it attempts to duplicate what EDD core is doing here:
https://github.com/easydigitaldownloads/edd-cross-sell-upsell/blob/master/includes/template-functions.php#L166

So this bug would likely happen to anyone/anything filtering the `edd_download_class` filter. It just so happens that Themedd happens to filter that, but the real problem here is that Cross Sell and Upsell does not accept the same number of arguments as EDD core, when applying the same filter. 

Therefore I am moving this to the EDD Cross Sell and Upsell repo.
